select top 20 * from shopping_behaviour

--Q1. what is the total revenue generated by male vs female customers?
select gender, sum([purchase_amount_(usd)]) as revenue
from shopping_behaviour
group by gender

--Q2. which customers used discount but still spend more than average purchase amount
select customer_id,discount_applied,[purchase_amount_(usd)]
from shopping_behaviour
where discount_applied = 'Yes' and [purchase_amount_(usd)] > (select avg([purchase_amount_(usd)]) from shopping_behaviour)

--Q3. which are the top 5 products with the highest average review rating
select top 5 item_purchased,round(avg(review_rating),2) as 'Average product rating'
from shopping_behaviour
group by item_purchased
order by avg(review_rating)  desc

--Q4. compare the average purchase amount between standard and express shipping
select shipping_type,avg([purchase_amount_(usd)]) as 'average_purchase_amount'
from shopping_behaviour
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. do subscribed customer spend more? compare average spend and total revenue
--between subscribers and non-subscribers
select subscription_status,
count(customer_id) as 'customers',
round(avg([purchase_amount_(usd)]),2) as 'average_amount',
sum([purchase_amount_(usd)]) as 'total amount'
from shopping_behaviour
group by subscription_status

--Q6. which 5 products have the highest percentage of purchases with discounts applied?
select top 5 item_purchased,
round(100*sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from shopping_behaviour
group by item_purchased
order by discount_rate desc

--Q7(IMP). segment customers into New, Returning and Loyal based on their total
--number of previous purchases and show the count of each segment.
with customer_type as(
select customer_id,previous_purchases,
case
	when previous_purchases = 1 then 'New'
	when previous_purchases between 1 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from shopping_behaviour
)
select customer_segment,count(*) as total_customers
from customer_type
group by customer_segment

--Q8. what are top 3 most purchased product within each category?
with item_counts as (
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from shopping_behaviour
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <= 3

--Q9. are customers who are repeat buyers(more than 5 previous purchases) also
--likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from shopping_behaviour
where previous_purchases>5
group by subscription_status

--Q10. what is the revenue contribution of each age group?
select age_group,sum([purchase_amount_(usd)]) as total_revenue
from shopping_behaviour
group by age_group
order by total_revenue desc
